name: Check for new releases of docker/cli
on:
  schedule:
    - cron: '55 8 * * *'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  check-for-token:
    outputs:
      has-token: ${{ steps.calc.outputs.HAS_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - id: calc
      run: echo "HAS_SECRET=${HAS_SECRET}" >> "${GITHUB_OUTPUT}"
      env:
        HAS_SECRET: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW != '' }}

  check-docker-cli:
    needs: check-for-token
    if: needs.check-for-token.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
          cache: yarn
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache-dependency-path: src/go/**/go.sum

      - run: yarn install --frozen-lockfile

      - run: yarn dcmonitor
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
