name: e2e tests on Mac M1

on:
  workflow_dispatch:
  schedule:
  - cron: '15 8 * * 1-5'

jobs:

  e2e-tests:
    timeout-minutes: 45
    runs-on: [self-hosted, macos-latest, arm64]
    env:
      M1: 1
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: main
      - uses: ./.github/actions/yarn-install
      - name: Disable admin-access before start up
        run: |
          mkdir -p $HOME/Library/Preferences/rancher-desktop
          touch $HOME/Library/Preferences/rancher-desktop/settings.json
          cat <<EOF > $HOME/Library/Preferences/rancher-desktop/settings.json
          {
            "version": 5,
            "application": {
              "adminAccess": false
              "updater":  { "enabled": false },
            },
            "virtualMachine" {
              "memoryInGB": 6,
            },
            "pathManagementStrategy": "rcfiles"
          }
          EOF
      - name: Run Rancher Desktop in dev
        run: |
          yarn dev -- --no-modal-dialogs &
          sleep 200
          $HOME/.rd/bin/rdctl shutdown
          wait
      - name: Run e2e Tests
        continue-on-error: false
        run: yarn test:e2e
      - name: Failed tests
        if: failure()
        run: mkdir -p ./e2e/reports
      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
      - name: Cleanup test environment
        run: |
          #set -x
          cd $HOME/Library
          pushd Logs/rancher-desktop
          for x in *.log ; do
           echo -n '' > $x
          done
          popd
          rm -fr "Application Support/rancher-desktop"
          rm -fr Preferences/rancher-desktop
          rm -fr Caches/rancher-desktop/k3s-versions.json
          cd $HOME/.rd/bin
          for x in helm kubectl nerdctl docker ; do
           if [[ -L $x ]] ; then # && $(readlink $x):]] ; then
           rm -f $x
           fi
          done
        if: always()
      - name: End stray processes
        run: |
          ps auxww | grep qemu
          ps auxww | grep rancher | grep -vi -e goland
        if: always()
