name: Update external dependencies
on:
  schedule:
    - cron: '23 8 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-token:
    outputs:
      has-token: ${{ steps.calc.outputs.HAS_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - id: calc
      run: echo "HAS_SECRET=${HAS_SECRET}" >> "${GITHUB_OUTPUT}"
      env:
        HAS_SECRET: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW != '' }}

  check-update-versions:
    needs: check-for-token
    if: needs.check-for-token.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: yarn install --frozen-lockfile

      - run: yarn rddepman
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
