# This workflow builds the Rancher Desktop Extensions Host APIs testing image
# and publishes it.

name: RDX Host APIs Testing image
on:
  push:
    branches: [ main ]
    paths: [ 'bats/tests/extensions/testdata/**' ]
  workflow_dispatch: {}
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/rdx-host-api-test
        tags: type=raw,value=latest,enable={{ is_default_branch }}
    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        build-args: variant=host-apis
        context: bats/tests/extensions/testdata
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
