# This workflow builds the Rancher Desktop Extensions Host APIs testing image
# and publishes it.

name: RDX Host APIs Testing image
on:
  push:
    branches: [ main ]
    paths: [ 'bats/tests/extensions/testdata/**' ]
  workflow_dispatch: {}
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/rdx-host-api-test
        tags: type=raw,value=latest,enable={{ is_default_branch }}
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@v4
      with:
        build-args: variant=host-apis
        context: bats/tests/extensions/testdata
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
