# This workflow builds the Rancher Desktop Extensions Host APIs testing image
# and publishes it.

name: RDX Host APIs Testing image
on:
  push:
    branches: [ main ]
    paths: [ 'bats/tests/extensions/testdata/**' ]
  workflow_dispatch: {}
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
    - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/rdx-host-api-test
        tags: type=raw,value=latest,enable={{ is_default_branch }}
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        build-args: variant=host-apis
        context: bats/tests/extensions/testdata
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
