name: "Release: Merge to main"

on:
  release:
    types:
    - created
    - published
    - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-for-token:
    outputs:
      has-token: ${{ steps.calc.outputs.HAS_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - id: calc
      run: echo "HAS_SECRET=${HAS_SECRET}" >> "${GITHUB_OUTPUT}"
      env:
        HAS_SECRET: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW != '' }}

  create-pr:
    needs: check-for-token
    if: needs.check-for-token.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: ./.github/actions/yarn-install
    - run: node scripts/ts-wrapper.js scripts/release-merge-to-main.ts
      env:
        GITHUB_WRITE_TOKEN: ${{ github.token }}
        GITHUB_PR_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
