# This workflow downloads artifacts from a (by default, draft) release and runs
# a short smoke test where the application is installed and run and immediately
# shut down.
# Since we need contents-write permissions to look at draft releases, we
# actually download the artifacts in a smaller job, then upload them into the
# run and download it _again_ in the second (per-platform) job where no
# permissions are required.
name: Release smoke test
permissions: {}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: >
          Download artifacts from release with this tag, rather than picking the
          first draft release.
        type: string

jobs:
  download-artifacts:
    name: Find release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to list draft releases
    env:
      RELEASE_TAG: ${{ inputs.tag }}
    steps:
    - name: Find release
      if: inputs.tag == ''
      run: >-
        set -o xtrace;
        printf "RELEASE_TAG=%s\n" >>"$GITHUB_ENV"
        "$(gh api repos/${{ github.repository }}/releases
        --jq 'map(select(.draft))[0].tag_name')"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Download artifacts
      run: |
        if [[ -z "$RELEASE_TAG" ]]; then
          echo "Failed to find release tag" >&2
          exit 1
        fi
        gh release download "$RELEASE_TAG" \
          --repo ${{ github.repository }} \
          --pattern '*.dmg' \
          --pattern '*.dmg.sha512sum' \
          --pattern '*.msi' \
          --pattern '*.msi.sha512sum' \
          --pattern 'rancher-desktop-linux-*.zip' \
          --pattern 'rancher-desktop-linux-*.zip.sha512sum'
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Download AppImage
      run: |
        branch=$(cut -d. -f1,2 <<< "${RELEASE_TAG#v}")
        read -r artifact_name < <(
          curl "${OBS_DOWNLOAD_URL}?jsontable" \
            | jq --raw-output ".data[].name | select(endswith(\".AppImage\")) | select(contains(\".release${branch}.\"))"
          )
        curl -L -o rancher-desktop.AppImage "${OBS_DOWNLOAD_URL}${artifact_name}"
        chmod a+x rancher-desktop.AppImage
      env:
        OBS_DOWNLOAD_URL: https://download.opensuse.org/download/repositories/isv:/Rancher:/dev/AppImage/

    - name: Upload macOS aarch-64 artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: application-macos-aarch64.zip
        if-no-files-found: error
        path: |
          *.aarch64.dmg
          *.aarch64.dmg.sha512sum
    - name: Upload macOS x86_64 artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: application-macos-x86_64.zip
        if-no-files-found: error
        path: |
          *.x86_64.dmg
          *.x86_64.dmg.sha512sum
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: application-win32.zip
        if-no-files-found: error
        path: |
          *.msi
          *.msi.sha512sum
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: application-linux.zip
        if-no-files-found: error
        path: |
          rancher-desktop-linux-*.zip
          rancher-desktop-linux-*.zip.sha512sum
    - name: Upload Linux AppImage
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: application-linux.AppImage
        if-no-files-found: error
        path: rancher-desktop.AppImage

  smoke-test:
    name: Smoke test
    needs: download-artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
        - { platform: macos-aarch64, runs-on: macos-14 }
        - { platform: macos-x86_64, runs-on: macos-13 }
        - { platform: win32, runs-on: windows-latest }
        - { platform: linux, runs-on: ubuntu-latest }
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up environment
      uses: ./.github/actions/setup-environment

    - name: "Linux: Set startup command"
      if: runner.os == 'Linux'
      run: echo "EXEC_COMMAND=$EXEC_COMMAND" >> "$GITHUB_ENV"
      env:
        EXEC_COMMAND: >-
          exec xvfb-run --auto-servernum
          --server-args='-screen 0 1280x960x24'


    - name: Set log directory
      shell: bash
      # Use node here to do path manipulation to get correct Windows paths.
      run: >-
        node --eval='console.log("RD_LOGS_DIR=" + require("path").join(process.cwd(), "logs"));'
        >> "$GITHUB_ENV"

    - name: Download artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: application-${{ matrix.platform }}.zip
    - run: ${{ env.EXEC_COMMAND }} .github/workflows/smoke-test/smoke-test.sh
      shell: bash
    - name: Upload logs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: logs-${{ matrix.platform }}.zip
        path: ${{ github.workspace }}/logs
        if-no-files-found: warn

  appimage-smoke-test:
    name: Smoke test AppImage
    needs: download-artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
        - { id: opensuse, image: "registry.opensuse.org/opensuse/tumbleweed:latest" }
        - { id: rocky, image: "rockylinux/rockylinux:9" }
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged
    steps:
    - name: Install dependencies
      run: |
        source /etc/os-release
        for id in $ID $ID_LIKE; do
          case $id in
            suse|opensuse)
              zypper --non-interactive install --recommends \
                fuse gawk git GraphicsMagick gtk3-tools jq mozilla-nss sudo xvfb-run
              break;;
            rocky|rhel|centos)
              dnf install --assumeyes \
                https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
              /usr/bin/crb enable # spellcheck-ignore-line
              dnf install --assumeyes \
                at-spi2-atk cups-libs git GraphicsMagick gtk3 jq \
                libva nss procps-ng sudo xorg-x11-server-Xvfb
              break;;
          esac
        done
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Set up environment
      uses: ./.github/actions/setup-environment

    - name: Set up user
      run: |
        useradd --create-home --user-group ci-user
        export LOGS_DIR=$PWD/logs
        export RD_LOGS_DIR=$LOGS_DIR/rd
        echo "LOGS_DIR=$LOGS_DIR" >> "$GITHUB_ENV"
        echo "RD_LOGS_DIR=$RD_LOGS_DIR" >> "$GITHUB_ENV"
        mkdir -p $LOGS_DIR
        chown ci-user "$LOGS_DIR"
        sudo --user=ci-user mkdir "$RD_LOGS_DIR"

    - name: Download AppImage
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: application-linux.AppImage

    - name: Start Rancher Desktop
      id: start-rancher-desktop
      run: |
        set -o xtrace
        chmod a+x rancher-desktop.AppImage
        inner_command=(
          xvfb-run
            --auto-servernum
            --server-args='-screen 0 1280x960x24'
          ./rancher-desktop.AppImage
            --no-sandbox
            --enable-logging=stderr
            --v=1
            --no-modal-dialogs
            --kubernetes.enabled
        )
        sudo --user=ci-user \
          RD_DEBUG_ENABLED=1 RD_LOGS_DIR=$RD_LOGS_DIR RD_TEST=smoke \
          script \
            --log-out $LOGS_DIR/appimage-${{ matrix.id }}.log \
            --command "${inner_command[*]@Q}" \
          &
        echo "TARGET_PID=$!" >> "$GITHUB_ENV"
    - name: Wait for backend
      shell: sudo --user=ci-user bash --noprofile --norc -eo pipefail {0}
      run: |
        deadline=$(( $(date +%s) + 10 * 60 ))
        state=UNKNOWN
        while [[ $(date +%s) -lt $deadline ]]; do
          printf "Waiting for backend: (%s) %s/%s\n" "$state" "$(date)" \
            "$({ date --date="@$deadline" || date -j -f %s "$deadline"; } 2>/dev/null)"

          if [[ ! -d /proc/$TARGET_PID ]]; then
            echo "Process $TARGET_PID exited" >&2
            exit 1
          fi
          rd_pid=$(pidof --separator $'\n' rancher-desktop | sort -n | head -n 1 || echo missing)
          if [[ ! -e /proc/$rd_pid/exe ]]; then
            state=NOT_RUNNING
            sleep 10
            continue
          fi
          if [[ ! -e $HOME/.local/share/rancher-desktop/rd-engine.json ]]; then
            state=NO_SERVER_CONFIG
            sleep 10
            continue
          fi
          rdctl=$(dirname "$(readlink /proc/$rd_pid/exe)")/resources/resources/linux/bin/rdctl
          state=$("$rdctl" api /v1/backend_state || echo '{"vmState": "NO_RESPONSE"}')
          state=$(jq --raw-output .vmState <<< "$state")
          case "$state" in
            ERROR)
              echo "Backend reached error state." >&2
              exit 1;;
            STARTED|DISABLED)
              printf "PID %s has reached state %s, accepting\n" "$rd_pid" "$state"
              exit 0;;
            *)
              printf "Backend state: %s\n" "$state";;
          esac
          sleep 10
        done

        echo "Timed out waiting for backend to stabilize." >&2
        printf "Current time: %s\n" "$(date)" >&2
        printf "Deadline: %s\n" >&2 \
            "$({ date --date="@$deadline" || date -j -f %s "$deadline"; } 2>/dev/null)"
        exit 1

    - name: Take screenshot
      if: failure() && steps.start-rancher-desktop.outcome == 'success'
      continue-on-error: true
      shell: >-
        sudo --user=ci-user LOGS_DIR=$LOGS_DIR
        bash --noprofile --norc -eo pipefail {0}
      run: |
        set -o xtrace -o errexit
        PID=$(pidof rancher-desktop.AppImage || echo missing)
        if [[ ! -r /proc/$PID/environ ]]; then
          echo "Rancher Desktop is not running" >&2
          exit 0
        fi
        export $(gawk 'BEGIN { RS="\0"; FS="=" } ($1 == "DISPLAY" || $1 == "XAUTHORITY") { print }' \
          < /proc/$PID/environ)
        env
        export MAGICK_DEBUG=All # spellcheck-ignore-line
        gm import -window root -verbose $LOGS_DIR/screenshot-${{ matrix.id }}.png

    - name: Upload logs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: logs-appimage-${{ matrix.id }}.zip
        path: ${{ github.workspace }}/logs
        if-no-files-found: warn
