name: Check Spelling

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request:
    branches:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      security-events: write # To be able to write SARIF events
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    env:
      UPLOAD_SARIF_LIMITED: '' # Set by `yarn lint:spelling`.
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - uses: ./.github/actions/yarn-install
    - uses: ./.github/actions/setup-environment
    - run: sudo apt-get install cpanminus

    - name: Check Spelling
      run: yarn lint:spelling
      env:
        GITHUB_TOKEN: ${{ github.token }} # Needed to generate SARIF reports.
        RD_LINT_SPELLING: 1

    - name: Upload SARIF report
      # Use the limited report since if we have more than 25k errors nobody is
      # going read through it all anyway.
      if: always() && env.UPLOAD_SARIF_LIMITED != ''
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: check-spelling
        sarif_file: ${{ env.UPLOAD_SARIF_LIMITED }}
