name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/setup-go@v2
      with:
        stable: 'false' # Remove once RC suffix is removed
        go-version: '1.18.0-rc1'
    - run: npm ci
    - run: npm run lint:nofix
    - run: npm test
