name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'
        cache: yarn
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21'
        cache-dependency-path: src/go/**/go.sum
    - run: pip install setuptools
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint:nofix
    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0
    - run: make -C bats lint
    - run: yarn test
