name: Check for unreleased changes
on:
  schedule:
    - cron: '48 8 * * *'
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  check-for-token:
    outputs:
      has-token: ${{ steps.calc.outputs.HAS_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - id: calc
      run: echo "HAS_SECRET=${HAS_SECRET}" >> "${GITHUB_OUTPUT}"
      env:
        HAS_SECRET: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW != '' }}

  check-unreleased-changes:
    needs: check-for-token
    if: needs.check-for-token.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: yarn

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install setuptools
      - run: yarn install --frozen-lockfile

      - run: yarn ucmonitor
        env:
          GITHUB_TOKEN: ${{ secrets.RUN_WORKFLOW_FROM_WORKFLOW }}
