name: e2e tests on Windows

on:
  schedule:
    - cron: '13 5 * * 1-5'
  workflow_dispatch: {}
defaults:
  run:
    shell: powershell
jobs:

  e2e-tests:
    timeout-minutes: 90
    runs-on: [self-hosted, Windows, X64, win11]
    steps:
      - run: wsl --unregister rancher-desktop
        continue-on-error: true
      - run: wsl --unregister rancher-desktop-data
        continue-on-error: true
      - run: Remove-Item -Path "$HOME/AppData/Local/rancher-desktop" -Recurse -Force -ErrorAction Ignore
      - name: Remove golang module cache
        run: Remove-Item -Path "$HOME/go/pkg/mod" -Recurse -Force -ErrorAction Ignore
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      # For compatibility with runners without yarn, we need to install node
      # once, install yarn, then install node again to get caching.
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
      - run: npm install --global yarn
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
          cache: yarn
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache: 'true'
          cache-dependency-path: src/go/**/go.sum
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install setuptools
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run e2e Tests
        run: yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
      - name: Upload failure reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
