name: e2e tests on Windows

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request: {}

defaults:
  run:
    shell: powershell
jobs:
  check-paths:
    uses: ./.github/workflows/paths-ignore.yaml
  e2e-tests:
    needs: check-paths
    if: needs.check-paths.outputs.should-run == 'true'
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/yarn-install
      - name: Run e2e Tests
        run: yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
      - name: Upload failure reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: e2etest-artifacts
          path: ./e2e/reports/*
